# Generated by Django 3.2.3 on 2021-05-25 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0002_auto_20210523_0604'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shrinkage',
            old_name='wrap',
            new_name='warp',
        ),
    ]
