# Generated by Django 3.2.3 on 2021-05-27 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0003_rename_wrap_shrinkage_warp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fabriccomposition',
            name='fiber',
        ),
        migrations.RemoveField(
            model_name='fabriccomposition',
            name='percentage',
        ),
        migrations.CreateModel(
            name='FiberPercentage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('percentage', models.PositiveIntegerField()),
                ('fiber', models.ForeignKey(db_column='fiber', on_delete=django.db.models.deletion.PROTECT, to='fabric.fiber')),
            ],
            options={
                'verbose_name': 'Fiber Percentage',
                'verbose_name_plural': 'Fiber Percentages',
                'db_table': 'fiber_percentages',
            },
        ),
        migrations.CreateModel(
            name='FiberComposition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('fabric_composition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabric.fabriccomposition')),
                ('fiber_percentage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabric.fiberpercentage')),
            ],
            options={
                'verbose_name': 'Fiber Composition',
                'verbose_name_plural': 'Fiber Compositions',
                'db_table': 'fiber_compositions',
            },
        ),
        migrations.AddField(
            model_name='fabriccomposition',
            name='fiber_percentages',
            field=models.ManyToManyField(through='fabric.FiberComposition', to='fabric.FiberPercentage'),
        ),
    ]
