# Generated by Django 3.2.3 on 2021-05-27 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0004_auto_20210527_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='barcode',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
