# Generated by Django 3.2.3 on 2021-05-29 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0005_fabric_barcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabric',
            name='code',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
