# Generated by Django 3.2.3 on 2021-06-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0006_auto_20210529_0437'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fabric',
            old_name='availability',
            new_name='initial_availability',
        ),
        migrations.AddField(
            model_name='fabric',
            name='last_availability',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FabricDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('initial_availability', models.PositiveIntegerField(blank=True, null=True)),
                ('used_yds', models.PositiveIntegerField(blank=True, null=True)),
                ('last_availability', models.PositiveIntegerField(blank=True, null=True)),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fabric.fabric')),
            ],
            options={
                'verbose_name': 'Fabric',
                'verbose_name_plural': 'Fabrics',
                'db_table': 'fabric_details',
            },
        ),
    ]
