# Generated by Django 3.2.3 on 2021-06-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0007_auto_20210622_0919'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabricdetail',
            options={'verbose_name': 'Fabric Detail', 'verbose_name_plural': 'Fabric Details'},
        ),
    ]
