# Generated by Django 3.2.3 on 2021-06-23 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0007_alter_fibercomposition_unique_together'),
        ('fabric', '0008_alter_fabricdetail_options'),
    ]

    operations = [
    ]
