# Generated by Django 3.2.3 on 2021-06-26 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0009_merge_20210623_1010'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='fiberpercentage',
            unique_together={('fiber', 'percentage')},
        ),
    ]
