# Generated by Django 3.2.3 on 2021-07-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0010_alter_fiberpercentage_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fabric',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fabric', 'verbose_name_plural': 'Fabrics'},
        ),
        migrations.AlterModelOptions(
            name='fabriccomposition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fabric Composition', 'verbose_name_plural': 'Fabric Compositions'},
        ),
        migrations.AlterModelOptions(
            name='fabricconstruction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fabric Construction', 'verbose_name_plural': 'Fabric Constructions'},
        ),
        migrations.AlterModelOptions(
            name='fabricdetail',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fabric Detail', 'verbose_name_plural': 'Fabric Details'},
        ),
        migrations.AlterModelOptions(
            name='fabrictype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fabric Type', 'verbose_name_plural': 'Fabric Types'},
        ),
        migrations.AlterModelOptions(
            name='fiber',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fiber', 'verbose_name_plural': 'Fibers'},
        ),
        migrations.AlterModelOptions(
            name='fibercomposition',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fiber Composition', 'verbose_name_plural': 'Fiber Compositions'},
        ),
        migrations.AlterModelOptions(
            name='fiberpercentage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Fiber Percentage', 'verbose_name_plural': 'Fiber Percentages'},
        ),
        migrations.AlterModelOptions(
            name='shrinkage',
            options={'ordering': ['-created_at'], 'verbose_name': 'Shrinkage', 'verbose_name_plural': 'Shrinkage'},
        ),
    ]
