# Generated by Django 3.2.3 on 2021-07-06 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0012_auto_20210706_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiberpercentage',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
