# Generated by Django 3.2.3 on 2021-07-06 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0013_alter_fiberpercentage_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='mill_reference',
            field=models.CharField(max_length=255),
        ),
    ]
