# Generated by Django 3.2.3 on 2021-07-14 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0014_alter_fabric_mill_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fabric',
            name='appearance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fabric.appearance'),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='weave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fabric.weave'),
        ),
    ]
