# Generated by Django 3.2.3 on 2021-06-14 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_type',
            field=models.ForeignKey(db_column='supplier_type', null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.suppliertype'),
        ),
    ]
