# Generated by Django 3.2.3 on 2021-06-14 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0002_alter_supplier_supplier_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='country',
            field=models.ForeignKey(db_column='country', null=True, on_delete=django.db.models.deletion.PROTECT, to='supplier.country'),
        ),
    ]
