# Generated by Django 3.2.3 on 2021-07-05 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0003_alter_supplier_country'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['-created_at'], 'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'ordering': ['-created_at'], 'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
        migrations.AlterModelOptions(
            name='suppliertype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Supplier Type', 'verbose_name_plural': 'Supplier Types'},
        ),
    ]
