# Generated by Django 3.2.3 on 2021-06-22 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fabric', '0007_auto_20210622_0919'),
        ('style', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Wash Type',
                'verbose_name_plural': 'Wash Types',
                'db_table': 'wash_types',
            },
        ),
        migrations.RemoveField(
            model_name='style',
            name='wash',
        ),
        migrations.AddField(
            model_name='style',
            name='fabric_details',
            field=models.ForeignKey(db_column='fabric_details', default='', on_delete=django.db.models.deletion.PROTECT, to='fabric.fabricdetail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='style',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='style',
            name='wash_type',
            field=models.ForeignKey(db_column='wash_type', default='', on_delete=django.db.models.deletion.PROTECT, to='style.washtype'),
            preserve_default=False,
        ),
    ]
