# Generated by Django 3.2.3 on 2021-07-03 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0002_auto_20210622_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='barcode',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='style',
            name='code',
            field=models.CharField(blank=True, max_length=13),
        ),
    ]
