# Generated by Django 3.2.3 on 2021-07-06 04:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0005_auto_20210705_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
                'db_table': 'properties',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='style',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='style',
            name='designer',
            field=models.ForeignKey(db_column='designers', on_delete=django.db.models.deletion.PROTECT, to='style.designer'),
        ),
        migrations.AlterField(
            model_name='style',
            name='wash_type',
            field=models.ForeignKey(db_column='wash_types', on_delete=django.db.models.deletion.PROTECT, to='style.washtype'),
        ),
        migrations.AlterModelTable(
            name='designer',
            table='designers',
        ),
        migrations.AddField(
            model_name='style',
            name='Property',
            field=models.ForeignKey(db_column='properties', default='', on_delete=django.db.models.deletion.PROTECT, to='style.property'),
            preserve_default=False,
        ),
    ]
