# Generated by Django 3.2.3 on 2021-07-06 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('style', '0006_auto_20210706_1046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='Property',
            new_name='property',
        ),
    ]
